{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 25067,
          "sha512": "861c9a39cae3a5f7b950fc2846c8a55786ea5910d8888eb9154391807603259c13a5c6aab42b044076cd68728bc5126e5b084e33d0d7f51852afcef3475cdd25",
          "sha256": "1459f986e5ec6fabcc523369156a841ecec866f81004577fc11783b7dfcd4ec5",
          "sha1": "e57d4e8d9ad24bf549b6e20174c44026f365f65a",
          "md5": "d71f14cc5054c9ad0c365beef174742c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 25067,
          "sha512": "861c9a39cae3a5f7b950fc2846c8a55786ea5910d8888eb9154391807603259c13a5c6aab42b044076cd68728bc5126e5b084e33d0d7f51852afcef3475cdd25",
          "sha256": "1459f986e5ec6fabcc523369156a841ecec866f81004577fc11783b7dfcd4ec5",
          "sha1": "e57d4e8d9ad24bf549b6e20174c44026f365f65a",
          "md5": "d71f14cc5054c9ad0c365beef174742c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-sources.jar",
          "url": "flutter_secure_storage_release-1.0-sources.jar",
          "size": 12534,
          "sha512": "fcdbec471d1020aca7debb4980e3cea0b149e8b8580c5fb3b2c21ca8576ba704f7169a83c62db1c1ded8560f437ffbee69f49a5812d36b452bbf0f6930d27fe6",
          "sha256": "b1bca772397453d700fe173e49d629cdfc2a735732389f1ae6898b147a934087",
          "sha1": "19c22aced34c08b86837d9bcb1039e715f573657",
          "md5": "0bf72f214670f698fed4573890e558e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-javadoc.jar",
          "url": "flutter_secure_storage_release-1.0-javadoc.jar",
          "size": 307679,
          "sha512": "c33642fafe21475ddf9d0801ac6be11f5a6679d9cf549ec2d31ea915d709e3c784e59f24e7a7b383664e259cfed2596eb4a4fa46a2d23bbf112f74a3d50d9865",
          "sha256": "7ef55cc2ea9cb96b73af40e8ee7cd9340544e8778ad987a131b7645df0f8bf80",
          "sha1": "6b0bc59ff431a461cc4965f6cf56dd10f5e455a4",
          "md5": "5117fc3d2cc4edbb3434ce3808dbf140"
        }
      ]
    }
  ]
}
