{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 42488,
          "sha512": "ee410219ecbd5e4ec7cc34d9237cc97bc389a58f3640dd2bc5a5d95925c53c2d5bf9583253a0743c6360991dd1b0a71e8803de3b5abdd87d463e1b5b9903e093",
          "sha256": "7410a776b9c7df960c7c28218ed94d3f13cbc9ad6f499984c5dca584b86f6938",
          "sha1": "439bf5828506af67d5c8c7ba7c7a980b361801c5",
          "md5": "b986d640fcbddd795c7ac9a78750fd5a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 42488,
          "sha512": "ee410219ecbd5e4ec7cc34d9237cc97bc389a58f3640dd2bc5a5d95925c53c2d5bf9583253a0743c6360991dd1b0a71e8803de3b5abdd87d463e1b5b9903e093",
          "sha256": "7410a776b9c7df960c7c28218ed94d3f13cbc9ad6f499984c5dca584b86f6938",
          "sha1": "439bf5828506af67d5c8c7ba7c7a980b361801c5",
          "md5": "b986d640fcbddd795c7ac9a78750fd5a"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0-sources.jar",
          "url": "file_picker_debug-1.0-sources.jar",
          "size": 11292,
          "sha512": "6934d3e4ab9146e349471a11c4f53b19c742f677cc6686d21de93fc497534f73274b86e3f3ec2303f419ca4cb2638caf9e5782949925841b4aa329b9e5633a95",
          "sha256": "567c8d84a2aa6a6032316f8f491b21a5dcc23ab386f5b0cf333bb277b17db94d",
          "sha1": "050e0893e7be2da532a4ce3159e11ef66b30656a",
          "md5": "e74f61a98f12b510bc51302606a05d86"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0-javadoc.jar",
          "url": "file_picker_debug-1.0-javadoc.jar",
          "size": 307511,
          "sha512": "8c426b273a1c6399faab27d01e819a866c9e0f0e54b7e19da62661f57148d459ffc720814a2ffc9caae90f06a97e829255fca06e89379b6f7eec904f6f8d1274",
          "sha256": "b0b0529d91f66d1ad08e46604b18795b07ec1ff3d9cc48f4bc2be53c97c71066",
          "sha1": "f97682094ad30dff50d7e7ac0130c3790a1ad349",
          "md5": "c879578655145900a650845cad9042e6"
        }
      ]
    }
  ]
}
