{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 41415,
          "sha512": "37d1bed947cfccdb85fe46764931c70a27db35cf0b5e83f3986e322f4bd814ce592a5dc1619e32efdab17c10664c3ddb164e433d4f4b3e10584032abbc05cee3",
          "sha256": "ec43c26f7932c6dc35400169fcde7205fadd75c5f931afd84d0f90062c2feb53",
          "sha1": "987ddd679dd80a87c722679d294bf025b2313af0",
          "md5": "c9adc13dccf3e3127aae0f840c9d5e27"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 41415,
          "sha512": "37d1bed947cfccdb85fe46764931c70a27db35cf0b5e83f3986e322f4bd814ce592a5dc1619e32efdab17c10664c3ddb164e433d4f4b3e10584032abbc05cee3",
          "sha256": "ec43c26f7932c6dc35400169fcde7205fadd75c5f931afd84d0f90062c2feb53",
          "sha1": "987ddd679dd80a87c722679d294bf025b2313af0",
          "md5": "c9adc13dccf3e3127aae0f840c9d5e27"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0-sources.jar",
          "url": "file_picker_debug-1.0-sources.jar",
          "size": 11269,
          "sha512": "efadc062e05cfa2593fc57d9ced764c19fdaee7c754e94f97304751bd3b1478f4c79e5231cc7796a8b1ce3f32a336dc534f79559b3dea59e3c2c0589ba2b3b1e",
          "sha256": "d90f5f105db0c00f417dbc04586d479df8f920d8fb46993968ad64bad04f8504",
          "sha1": "4975e49956168d92255ec922bb66d21acfbb7682",
          "md5": "77d34369e0c07ee2a6bc59a30dbc11e2"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0-javadoc.jar",
          "url": "file_picker_debug-1.0-javadoc.jar",
          "size": 307512,
          "sha512": "e1fd56932b3921df42faf38af7b36d32caea3d955e85bb1fbc175f8363c7233e1163b19788a355a04f0c729072e12e53437ad8efcf97e3086537e4f98153a002",
          "sha256": "defa2301cfe7bdfe3c831e4a3ddab852bdb9544407ff65ac982d3c883405e0a8",
          "sha1": "f77d8acd6379981b0b5bda0608c595374c5b4358",
          "md5": "ef9cc0025b93974083369e35249fea32"
        }
      ]
    }
  ]
}
