{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 41415,
          "sha512": "eebedaae26039876c3f3bce1bef99e4f6e29fa43dad6f8d4129dce62a63bf7de5e586f83890b5b871e9397fb9ec4ac71bd3793256bc95ccc208a28afae7d68b0",
          "sha256": "f8217ed95b5b6378de307901283ff3924d00c7e71034ba641472f7489bbf86d7",
          "sha1": "ac5fe9c2346049a054949cecfa15135ee49526c5",
          "md5": "19f1cc3f7837424d50e7504e96d2d2a1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 41415,
          "sha512": "eebedaae26039876c3f3bce1bef99e4f6e29fa43dad6f8d4129dce62a63bf7de5e586f83890b5b871e9397fb9ec4ac71bd3793256bc95ccc208a28afae7d68b0",
          "sha256": "f8217ed95b5b6378de307901283ff3924d00c7e71034ba641472f7489bbf86d7",
          "sha1": "ac5fe9c2346049a054949cecfa15135ee49526c5",
          "md5": "19f1cc3f7837424d50e7504e96d2d2a1"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0-sources.jar",
          "url": "file_picker_profile-1.0-sources.jar",
          "size": 11269,
          "sha512": "efadc062e05cfa2593fc57d9ced764c19fdaee7c754e94f97304751bd3b1478f4c79e5231cc7796a8b1ce3f32a336dc534f79559b3dea59e3c2c0589ba2b3b1e",
          "sha256": "d90f5f105db0c00f417dbc04586d479df8f920d8fb46993968ad64bad04f8504",
          "sha1": "4975e49956168d92255ec922bb66d21acfbb7682",
          "md5": "77d34369e0c07ee2a6bc59a30dbc11e2"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0-javadoc.jar",
          "url": "file_picker_profile-1.0-javadoc.jar",
          "size": 307512,
          "sha512": "e1fd56932b3921df42faf38af7b36d32caea3d955e85bb1fbc175f8363c7233e1163b19788a355a04f0c729072e12e53437ad8efcf97e3086537e4f98153a002",
          "sha256": "defa2301cfe7bdfe3c831e4a3ddab852bdb9544407ff65ac982d3c883405e0a8",
          "sha1": "f77d8acd6379981b0b5bda0608c595374c5b4358",
          "md5": "ef9cc0025b93974083369e35249fea32"
        }
      ]
    }
  ]
}
