{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23648,
          "sha512": "f0683ae7cdd05f3b35772ee1805d9871aab1360e0cc87ef8118afd69d77ba65db2ce902b39a465bd544854c232f02f6001c64135bab83b58764a2bb848d75e8b",
          "sha256": "0ded16c458be7941602c63056d14e0994b8e032ce684497f687857640ae084fb",
          "sha1": "c71009a11f7902ba6a9314a2c847df8d59dc770e",
          "md5": "30e3b140f94ccdf0034bb3b9c9b3fc62"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23648,
          "sha512": "f0683ae7cdd05f3b35772ee1805d9871aab1360e0cc87ef8118afd69d77ba65db2ce902b39a465bd544854c232f02f6001c64135bab83b58764a2bb848d75e8b",
          "sha256": "0ded16c458be7941602c63056d14e0994b8e032ce684497f687857640ae084fb",
          "sha1": "c71009a11f7902ba6a9314a2c847df8d59dc770e",
          "md5": "30e3b140f94ccdf0034bb3b9c9b3fc62"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-sources.jar",
          "url": "url_launcher_android_profile-1.0-sources.jar",
          "size": 9242,
          "sha512": "29a9a51605b3b668076bc3bb70cdd13e5638067e4ca1eaa2df604991ebc1da6fe84f671603fe31e2ef775f86dbf35e0c3e6e994ac48210ba77b9ab2e6f3d1e36",
          "sha256": "28a118dbbe2d288d44c73d37c8297bc82da02bd1c85ecf15b8f7c2950ccc1535",
          "sha1": "7ecdc9e1d34de1ad1ed1dfa4ac5d1baf2d80cbde",
          "md5": "b6f2036cfeae530eb225a9109965ea68"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-javadoc.jar",
          "url": "url_launcher_android_profile-1.0-javadoc.jar",
          "size": 332781,
          "sha512": "f21ea3f58399edbd5e9e8a5d578022fa1af537ba7b13a2aca832e8910d18341c5b890636caa7904ccf869620e940bdcdcc4962a45cfe387f1cd11e295db40986",
          "sha256": "5ce90d0a09727ef62ba06b7058e6b7b0b541f61ceadc895595c3bcacd90ba537",
          "sha1": "7529f3a7448822d87545ecd293313681dff2deb3",
          "md5": "1fcd3eec3b9daeefa0b5d9b601a8d8a2"
        }
      ]
    }
  ]
}
