{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 10766,
          "sha512": "aa254c15dca8aab8a482904510a0ef4a22f340828d0e96ab265d74923fdad188223afb9e1b8a76ee96502096b7bfca914e817f6c7d688a4d6f4bde0eef44ffc4",
          "sha256": "6914525555cc511f633dc438e48b406375f4d41a07435c9ccca9c0e40e85f477",
          "sha1": "0c3e01f5e8a547cc7cc51b325023a0d7ea48f9e9",
          "md5": "db7eb4622b6799c675e2339b855cbb26"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 10766,
          "sha512": "aa254c15dca8aab8a482904510a0ef4a22f340828d0e96ab265d74923fdad188223afb9e1b8a76ee96502096b7bfca914e817f6c7d688a4d6f4bde0eef44ffc4",
          "sha256": "6914525555cc511f633dc438e48b406375f4d41a07435c9ccca9c0e40e85f477",
          "sha1": "0c3e01f5e8a547cc7cc51b325023a0d7ea48f9e9",
          "md5": "db7eb4622b6799c675e2339b855cbb26"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-sources.jar",
          "url": "path_provider_android_profile-1.0-sources.jar",
          "size": 4121,
          "sha512": "98abfe49b0c49012cf74c573e26b0af84ff0b734f9b13ef74b5ee09b3731a8f699a41cbad0060a6f53788a35b595f6cea8b6d24a9b28fc28c55faf578ea78335",
          "sha256": "95e5edc3e2309e7fe549d0d67b05848a141eb5ea996c7e68ce2990e32191cb46",
          "sha1": "e0c3107497e5fa098fb6a873e214796778aee5d7",
          "md5": "6fb2208a851ccf1b24b54473fb99bc03"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-javadoc.jar",
          "url": "path_provider_android_profile-1.0-javadoc.jar",
          "size": 294213,
          "sha512": "a2f899778f0dd05b1cbe4e9ab2d7b34d1e283ebf6c1c50d1d944b9aaa322edbcee99e599ce70e5d7c9fc07fd6446b5b7d72374c7e264b37c1ed789e6aabcaf64",
          "sha256": "bc00acdb135876ed8359fd6f92307ffc2f2531d7c80bf1cc72158637016cd853",
          "sha1": "a6ba9feb95714a0d6d0f8637c40dced2a8458d30",
          "md5": "f53c9299569bf88bf654746fc341293a"
        }
      ]
    }
  ]
}
